sudo: required
services:
- docker
language: bash
script:
- make
- ls -la
- find . -name '*.apk'
- cp torgi-logger-debug.apk torgi-logger-debug_${TRAVIS_TAG}.apk
- cp torgi-logger-release-unsigned.apk torgi-logger-release-unsigned_${TRAVIS_TAG}.apk
- cp torgi-viewer-debug.apk torgi-viewer-debug_${TRAVIS_TAG}.apk
- cp torgi-viewer-release-unsigned.apk torgi-viewer-release-unsigned_${TRAVIS_TAG}.apk
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push sofwerx/torgi:${TRAVIS_TAG}
branches:
  only:
  - master
  - travis-only
  - "/^v\\d.*$/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "${GITHUB_TOKEN}"
  file:
  - torgi-logger-debug_${TRAVIS_TAG}.apk
  - torgi-logger-release-unsigned_${TRAVIS_TAG}.apk
  - torgi-viewer-debug_${TRAVIS_TAG}.apk
  - torgi-viewer-release-unsigned_${TRAVIS_TAG}.apk
  on:
    tags: true
    repo: "${TRAVIS_REPO_SLUG}"
notifications:
  slack:
    rooms:
      secure: mlKHAU847yNmjblLRiLoWKlXUhi5XrYy4qqeShocfshbnsL399XOoVfGmpifVMEBpprrMg52r5gED9GlC2dlAt2Sv9hVKlBea0U4h4t6+eu06OpTjujEJZYoCKSCDdidwr2LZCJhhoWHBkSYzPZ/LQgdgoZYg2x6fOXX+HiEEBNUvPiwKeTlyiWBDkZBqrAcjvVdMYGLvuzFao1TFlhwmCoJs7Ff3rry6kWVa2gJC1xS2cvLnIg+9CY6vHBo0gwJX39TowhMAZbhiAUjoVciofV6KSnwl95sROJb8ZHQh2Uzlut5CfJcr+tI/SYz2uObKSnQbjkbB/W/6agr741onJd0KKQLB/PyHsO5zXi+dx1RjYoOnzalT5OBZmI14dq3Yx3Mg4R/0C08yLpwjmBZHmbyu7dtEFZHKLwo8OYr9KnMUp3ovTqK6jlKbVa5lP+NQojx1ZUyRs6ufgwaSlFei4kCcl0R/zLcF7wFBhCASQTkI/BIelODcglBF8H4Ec9/Bmsli0D21QS86o2LPjsQx4y93W69e0Gl5xf1QZtyY/Kz9bYFFX4BNuXggEjInL9NDTX+VU+dn23edEdvgD+418/9OSuiKLkC4GzntOkiWxIg0EBDKrZBNriJlAZPf3RDrM72cS3cJj/zVZhg3pcD94PkHGABoUwwAB7RnFY5iEE=
